### ISSUE TITLE
[GoodID-UI] - GoodID Card

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#116]
### Business description
The GoodId card is used to show a user any data where a certificate has been given out for by the GoodDollar protocol.

### Design reference
Complete design: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=12308-14680&mode=design&t=AVvxWSGVkZj5B023-4

Design preview:
![image](https://github.com/GoodDollar/GoodWeb3-Mono/assets/6606028/339b7e8f-a52b-4056-828c-b58468ff739a)

### Technical implementation
The card will be used in different flows and screens.
1. [The onboard flow](https://github.com/GoodDollar/GoodWeb3-Mono/issues/138)
2. [The segmentation flow](https://github.com/GoodDollar/GoodWeb3-Mono/issues/140)
3. [Gooddapp post-upgrade good-id page](https://github.com/GoodDollar/GoodProtocolUI/issues/546) 

### Acceptance Criteria
- [x] - should show the verified data of a GoodID verified user
- [x] - should show expiration date of their face-id
- [x] - should match design as defined in figma
- [x] - should implement the [useAggregatedCertificates](https://github.com/GoodDollar/GoodWeb3-Mono/blob/239667e484b79ac748b0304062d17d4db99c534b/packages/sdk-v2/src/sdk/goodid/hooks/useCertificates.ts#L119) hook

**Comment by vldkhh** [comment]
verified on storybook

**Comment by vldkhh** [comment]
verified on prod
