### ISSUE TITLE
[GoodID-UI]: add modals

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#119]
### Motivation
Through the good-id flow several modals will be used, aligned in style just a different copy.

Design reference: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=11681-45791&mode=design&t=UKcUCbVhFeEmKt0y-0

### Acceptance Criteria
- [x] - should have an aligned structure for using/showing modals
- [x] - refactor RedirectNotice context to handle modals in general
- [x] - should add SignTX Modal: see what can be re-used from this old pr: https://github.com/GoodDollar/GoodWeb3-Mono/pull/90
- [x] - SignTxModal: should show if there are multiple sign tx in succession
- [x] - Add new design for verifyuniqueness modal

**Comment by vldkhh** [comment]
@L03TJ3 "rr.onDone is not a function" error displaying on Error Modal screen after accepting the offer. The screen is stucked after accepting the offer. 
<img width="1710" alt="Знімок екрана 2024-07-16 о 14 46 48" src="https://github.com/user-attachments/assets/2650c120-3131-4578-bd8f-5edb8f080b93">

**Comment by L03TJ3** [comment]
confirmed that above issue is a 'non-issue' (the rest part of the flow has not been added yet)

**Comment by L03TJ3** [comment]
@vldkhh pushed fix, moving back to qa

**Comment by vldkhh** [comment]
verified on prod
