### ISSUE TITLE
[GoodID-UI]: Offer screen

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#121]
### Business Description
https://github.com/GoodDollar/GoodDAPP/issues/4201

Design reference (for the first offer): https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=12308-14515&mode=design&t=4JK3RHTn9AR4HfdK-4

### Acceptance Criteria
- [x] Should have a start screen to show the available offer (should be generic)
- [x] Show a card with name of pool / The claim amount(s) / and url if they want to learn more about the pool
- [x] Show a list of qualifications needed for this pool (Could be existing credentials, or a custom one tailored for a specific pool)
- [x] Give option to user for accept or deny the offer. Once accepted it will guide the user to additional steps screens

**Comment by vldkhh** [comment]
verified on storybook

**Comment by vldkhh** [comment]
verified on prod
