### ISSUE TITLE
[GoodID-Flow]: RedTent offer

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#122]
### Description
The first eligible offer requires the uploading of a video selfie.

Aligned with ticket: https://github.com/GoodDollar/GoodDAPP/issues/4202

### Video storage requirements
- the videos are stored for a period of time (e.g. 6 weeks) in a secure place that
- we and third-party doing the pool should have access
- automatically deletes any videos over X weeks old?

### Undecided
- [x] Where to upload the video files to? (aws-storage)
- [x] should there be a flow for remind me later / users leaving (by mistake). should we re-trigger this flow?

## Detailed Description of Functionality
After a user is deemed eligible at the end of the [segmentation-flow](https://github.com/GoodDollar/GoodWeb3-Mono/issues/140) the offers-screen will be shown.

A user can choose here to accept the offer and start the flow for additional requirements of uploading a video selfie.
If a user clicks 'I don't want extra UBI' it will be navigated to the claim screen.

The screen with offers description will be shown with details of the video that needs to be uploaded.
When a user clicks next, the native screen for selecting and uploading a file pops-up.
After selecting a file, a user will see a thank you screen.
Tapping next will have a user start the claim-flow.

## Technical Implementation
**RedTent Controller**
- [handle upload to S3](https://github.com/GoodDollar/GoodWeb3-Mono/blob/e83b3e1bb9c6cf52dcabceceaf99dc3509a7edb0/packages/good-design/src/apps/redtent/RedtentController.tsx)
- 

**RedTent wizard**
- Implement the wizard-content [(done here)](https://github.com/GoodDollar/GoodWeb3-Mono/blob/e83b3e1bb9c6cf52dcabceceaf99dc3509a7edb0/packages/good-design/src/apps/redtent/RedtentWizard.tsx#L129)
- The wizard should have the following hierarchy
   - [Offers Screen](https://github.com/GoodDollar/GoodWeb3-Mono/issues/121)
   - [Video-upload screens](https://github.com/GoodDollar/GoodWeb3-Mono/issues/146)

[**SDK Implementation S3 upload**](https://github.com/GoodDollar/GoodWeb3-Mono/blob/e83b3e1bb9c6cf52dcabceceaf99dc3509a7edb0/packages/sdk-v2/src/sdk/redtent/sdk.ts#L1)
```
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

const s3 = new S3Client({
  region: "us-east-1",
  credentials: false,
  signer: { sign: async (request) => request },
});

const res = await s3.send(
  new PutObjectCommand({
    Bucket: "redtent",
    Key: "browser.txt",
    Body: "testing browser",
  })
)

```
### Acceptance Criteria
- [x] Should have a start screen describing the video requirements in line with the figma design
- [x] Should add a file upload function for a user to upload their recorded selfie
- [x] A thank you for submit screen from where a user is redirected to the claim page
- [x] should use aws sdk (or related methods) to take form data and send a uploaded file to our aws storage

### Design Reference
Design reference: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=12308-14574&mode=design&t=MWkbbMCLWLfUDM56-0

Preview design:
![image](https://github.com/GoodDollar/GoodWeb3-Mono/assets/6606028/d95a246d-0a63-4bcd-9e55-e18cdd873564)

**Comment by sirpy** [comment]
@decentralauren @patpedrosa 
The title of the issue doesnt make much sense

**Comment by sirpy** [comment]
@L03TJ3 i've added in the description a working example of uploading a file from browser to s3
specific domains will need to be approved for CORS

**Comment by L03TJ3** [comment]
@decentralauren @patpedrosa was a decision already made on a remind me later flow we discussed?

**Comment by decentralauren** [comment]
@L03TJ3 "remind me later" is ideal, though what's the LOE? 

In the near future, the user will be able to navigate to an "offers" area to find all eligible offers. This would make it much easier for them to recall / access offers that they skipped when first presented. Would love to have a way to continue offering if they select "remind me later" until this is built, as long as it's not a heavy lift.

**Comment by L03TJ3** [comment]
@decentralauren If you can go over the undecided section and share if we should handle this (so the users who mid redtent flow cut it off)

**Comment by decentralauren** [comment]
We do not need a "remind me" flow for MVP. If the user "skips" they can redo their FV to see the offers again.

**Comment by decentralauren** [comment]
@sanajamm - please update the design in this ticket when ready :)

**Comment by SanaJamm** [comment]
@decentralauren is this the right one?

screenshot:
<img width="959" alt="Screen Shot 2024-05-02 at 10 04 29" src="https://github.com/GoodDollar/GoodWeb3-Mono/assets/122018139/168415e7-1c87-4e76-8987-8c69c77de3e6">

https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=16765%3A105070&mode=design&t=lUAXCIhesIKDKXSl-1

**Comment by L03TJ3** [comment]
Moved [this](https://github.com/GoodDollar/GoodWeb3-Mono/issues/122#issuecomment-2089763460) to its own issue, so also removing the 'needs-design label'

**Comment by vldkhh** [comment]
verified on prod
