### ISSUE TITLE
[GoodID-UI]: New Claim page

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#123]
### Description
The claim page will get a new design and will also be able to show all the pools a user is verified for and can be claimed from

Design reference: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product-%F0%9F%92%B5?type=design&node-id=12324-22786&mode=design&t=MWkbbMCLWLfUDM56-0

### Acceptance Criteria
- [x] Update timer styling including billy animation  
- [x] Clicking the claim button initiates the claim transaction. If multiple pools, they are done consecutively
- [x] Update claim page design according to design
- [x] Total amount of all the pools combined should be shown at the top of the page
- [x] Old modals defined in ClaimButton should be removed and the flow should use the [new modals ](https://github.com/GoodDollar/GoodWeb3-Mono/issues/119)
- [x] should implement [Claim offers list](https://github.com/GoodDollar/GoodWeb3-Mono/issues/125)

**Comment by vldkhh** [comment]
verified on prod
