### ISSUE TITLE
[GoodID-SDK] - should redo fv check

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#127]
## Business Description
https://github.com/GoodDollar/GoodWeb3-Mono/issues/139

## Technical Implementation
- [x] add a hook that verifies the expiration date of facetek expiration

 expiry < 3
 - [x] - send to fv-flow
 expiry > 3
 - [ ] - send to segmentation

 
## Acceptance Criteria
Defined in business description

**Comment by vldkhh** [comment]
verified on prod
