### ISSUE TITLE
[GoodID]: Create a navigation widget for the id-flow screens

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#131]
## Business Description
Various good-id screens (segmentation / offers) need a way to navigate back to a previous screen.
The wallet has this built-in, but when the screens are loaded into an alternative dapp (like gooddapp) the screens should be loaded into some widget with pagination/navigate capabilities 

## Detailed Description of Functionality
*Provide detailed step-by-step functionality, including visual aids, edge cases, and special considerations.*

In example (design is a wip): https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=13573-59886&mode=design&t=g4v5MiAiAcB3vEnv-4

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 

TBD: 
- [ ] (What api's / sdk's could possibly be used)

 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*
- [ ] (Should include a list of testing points for QA how to verify design/functionality)
filled out by the development team or can contain suggestions._

**Comment by sirpy** [comment]
https://github.com/ezrafayet/use-wizard

**Comment by sirpy** [comment]
we'll use useWizard. see #122 redtent PR for example
