### ISSUE TITLE
Add storybook dev-environment

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#133]
Any requests not following requested format will make it take longer, or won't be taken up at all.

## Business Description
We have a playground called storybook where we create examples of features/UI components/flows.
usually this only for devs to run locally. I think it could be usefull to have a dev-environment set up for qa/product-review/design-review and more iteratively be able to track progress / how something would work

1. (optional: summary list of key features)

## Detailed Description of Functionality
Example vid of testing modals (its a work-in-progress when it comes to configurable fields etc, just to give an idea):
[Screencast from 29-02-24 20:07:13.webm](https://github.com/GoodDollar/GoodWeb3-Mono/assets/6606028/35883ed1-71bb-4a7b-be65-44d8149a7323)

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
- [ ] either deploy environment to vercel as new app / look into possibly deploying to github pages

 
## Acceptance Criteria
*Specify criteria that will be used to determine if the feature meets the requirements and functions correctly.*
- [ ] Make it easy for design/product/design to review progress and ui-components. Mostly usefull for agnostic type of components/flows

**Comment by decentralauren** [comment]
@L03TJ3 moved to In Sprint :)

**Comment by johnsmith-gooddollar** [comment]
@L03TJ3 Basic deployment was done:

**UI:** https://gooddollar-storybook.vercel.app/
**SDKv2:** https://gooddollar-storybook.vercel.app/sdk/

There are some errors/issues on some pages, this needs to be discussed/adjusted/fixed (probably tomorrow)

**Comment by L03TJ3** [comment]
@johnsmith-gooddollar thanks, will have a look tomorrow morning

**Comment by sirpy** [comment]
@johnsmith-gooddollar i've fixed the /sdk deployment
what other issues have you encountered?

**Comment by L03TJ3** [comment]
storybook is working both from dev and feature-branches, so closing this
