### ISSUE TITLE
[GoodID-flow] Onboarding flow

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodWeb3-Mono#138]
## Business Description
The onboarding screen is the new first screen for the FV flow. Its purpose is to explain to users the purpose of doing the face verification, creating a wallet, and to also collect from users their explicit consent to our terms of use and privacy policy. The onboarding screen also shows the GoodID Card component.

## Detailed Description of Functionality
A user arrives on this screen by clicking on the claim button. (See wallet/dapp implementation under 'Technical implementation' below for how this should work)

#### The [(onboard screen) ](https://github.com/GoodDollar/GoodWeb3-Mono/issues/115) can have various states:
New user, not connected:
- Should see the [(good id card) ](https://github.com/GoodDollar/GoodWeb3-Mono/issues/116) component blank. Should be invited to "Get" a GoodID. 

New user, connected but not face verified:
- Should see their wallet address on the wallet address field. Should be invited to "Get" a GoodID.

Existing user
- Should see all information available, along with their verification status and expiration date. Should be invited to "Renew" their GoodID.

#### The [(onboard screen) ](https://github.com/GoodDollar/GoodWeb3-Mono/issues/115) has two potential next routes
1. If a user is new, or an existing user expiry date is within the next three months it should navigate to the face-verification flow
The user is redirected to the fv-flow by using a passed-down navigate method (wallet), or it will be using the existing useFVLink (others, like gooddapp)

2. if it is an existing user, but their expiry date is longer than three months in the future the user is guided to the [segmentation screen](https://github.com/GoodDollar/GoodWeb3-Mono/issues/117) by loading the [SegmentationController](https://github.com/GoodDollar/GoodWeb3-Mono/blob/3f221b203045e61f9116b4fcc736ae1f4a1b0a54/packages/good-design/src/apps/goodid/controllers/SegmentationController.tsx#L14)

## Technical Implementation
[(Wallet implementation)](https://github.com/GoodDollar/GoodDAPP/issues/4254)
[(GoodDapp implementation)](https://github.com/GoodDollar/GoodProtocolUI/issues/550)

## Acceptance Criteria
_How we know if the feature is working as expected / how we test it._

- [ ] **Scenario: New user, not connected**
Given a new user who is not connected
When the onboarding screen is displayed
Then the GoodID card component should be blank
And the user should be invited to "Get" a GoodID

- [ ] **Scenario: New user, connected but not face verified**
Given a new user who is connected
When the onboarding screen is displayed
Then the user's wallet address should be shown in the wallet address field
And the user should be invited to "Get" a GoodID

- [ ] **Scenario: Existing user**
Given an existing user
When the onboarding screen is displayed
Then all available information, including name, photo, verification status and expiration date, should be shown
And the user should be invited to "Renew" their GoodID

**Comment by vldkhh** [comment]
verified on prod
