### ISSUE TITLE
[GoodID-Flow] Face Verification

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodWeb3-Mono#139]
## Business Description
_What the feature is and why we're doing it (business & user benefit)_

We want to implement new rules to the onboarding flow so that:

For users not yet Facetec verified > Facetec flow
For users already Facetec verified:
- Facetec expiry > 3 months from now: Send user to the segmentation
- Facetec expiry <3 months from now: Go through Facetec again

The Face Verification flow itself should not be changed, unless there are any technical requirements needed to be implemented.

## Detailed Description of Functionality
_Includes link to Figma, screen shots if applicable to describe step by step how the feature works, edge cases, and considerations. States etc should also be described here._

The rule check should happen after the onboarding page, according to the rules listed above. No design changes should be done to the existing face verification flow.

Design: https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=13532-19585&mode=design&t=nrTfOzoTxXG9tFKt-0

Design preview:
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59fd558f1f577476afd6297bd9df3d3d86ecb960/Screen%20Shot%202024-02-19%20at%2008.24.38.png" alt="Screen Shot 2024-02-19 at 08.24.38.png" />

## Technical Implementation
[_How we are going to build it._](https://github.com/GoodDollar/GoodWeb3-Mono/issues/127)

## Acceptance Criteria
_How we know if the feature is working as expected / how we test it._

- [ ] **Scenario: Face Verification Flow for Not Yet Facetec Verified**
  - Given a user who is not yet Facetec verified
  - When the user goes through the onboarding flow
  - Then the user should be directed to the Facetec flow

- [ ] **Scenario: Face Verification Flow for Users with Facetec Expiry > 3 months**
  - Given a user who is already Facetec verified and their Facetec expiry is more than 3 months from now
  - When the user goes through the onboarding flow
  - Then the user should be directed to the segmentation

- [ ] **Scenario: Face Verification Flow for Users with Facetec Expiry < 3 months**
  - Given a user who is already Facetec verified and their Facetec expiry is less than 3 months from now
  - When the user goes through the onboarding flow
  - Then the user should go through the Facetec flow again

**Comment by vldkhh** [comment]
verified on prod
