### ISSUE TITLE
[GoodID]: Video upload unhappy path:

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#159]
## Technical Implementation
- [x] - update redtent flow with new modals
- [x] - add a 'remind-me-later' flow

## Design Reference
screenshot:
<img width="935" alt="Screen Shot 2024-05-07 at 8 31 02" src="https://github.com/GoodDollar/GoodWeb3-Mono/assets/122018139/715b9b33-6d33-4c63-8e78-94598a0fc8ca">

Figma:
https://www.figma.com/file/ihw1PxBvLxacTHnN2aj4lC/3.-Product?type=design&node-id=16765%3A105070&mode=design&t=QplIkMw9aiMhuaJD-1

_Originally posted by @SanaJamm in https://github.com/GoodDollar/GoodWeb3-Mono/issues/146#issuecomment-2097480483_

**Comment by vldkhh** [comment]
verified on prod
