### ISSUE TITLE
[GoodID Upgrade] Feature Flag to control release

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodWeb3-Mono#184]
**Is your feature request related to a problem? Please describe.**
Need to be able to stage release of the GoodID upgrade, specifically:
- Round 1: By whitelisted wallet address
- Round 2: By country

**Describe the solution you'd like**
A feature flag managed in post-hog to control roll-out of the GoodID upgrade and GoodOffers, specifically to facilitate testing. This can copy the feature flag used for the Welcome Offer from GW1>GW2

**Comment by L03TJ3** [comment]
Moved issue because the feature-flag handling for this can/should be done on client-side

**Comment by L03TJ3** [comment]
For dev UAT we don't need a feature flag, the goodid offers are just enabled on dev by default.

Still need to add before release to production

**Comment by vldkhh** [comment]
@L03TJ3 could be closed?

**Comment by L03TJ3** [comment]
Yes, we have a feature-flag both on dev and in production that are based on country/whitelist
