### ISSUE TITLE
GoodID Bug: Header of updated claim flow is incorrect

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodWeb3-Mono#198]
**Bug Description**
New Claim flow shows "GoodID" in header. Should show "Claim" 

**Steps to Reproduce**
1. Go to the GoodWallet
2. Click "Claim" 

<img width="465" alt="Screenshot 2024-09-25 at 11 06 13 AM" src="https://github.com/user-attachments/assets/a25b181d-76f6-4fd4-a909-d4c761e3260b">
<img width="468" alt="Screenshot 2024-09-25 at 11 26 02 AM" src="https://github.com/user-attachments/assets/0cac8f4c-b45d-4981-98a2-385bbd359b6a">

**Expected Behavior**
That the header shows "Claim" throughout the entire claim flow (see all screens).

**Comment by vldkhh** [comment]
verified on prod
