### ISSUE TITLE
GoodID Claim Bug: Claim amounts displaying incorrectly 

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodWeb3-Mono#199]
**Bug Description**
Claim amounts are displaying incorrectly in the post-claim screen. The claim amount is inconsistent between this screen and the feed. See below.

**Steps to Reproduce**
1. Go to goodwallet
2. Click on claim
3. Claim successfully Red Tent and Celo G$ UBI
4. observe post-claim screen
5. observe feed display
...
<img width="468" alt="Screenshot 2024-09-25 at 11 24 44 AM" src="https://github.com/user-attachments/assets/9515f7b4-8a8d-46e5-9856-c6462be4e253">
<img width="468" alt="Screenshot 2024-09-25 at 11 26 02 AM" src="https://github.com/user-attachments/assets/1b48717c-612d-4910-86a6-8c9c5ac523e2">

**Expected Behavior**
That claim amounts be consistent across pre-claim, post-claim and feed.

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on prod
