### ISSUE TITLE
GoodID Claim Bug: Date and time are inconsistent

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodWeb3-Mono#200]
**Bug Description**
Claim time on past transaction differs between post-claim screen and feed
Claim date format is inconsistent between post-claim screen and feed

**Steps to Reproduce**
Go to goodwallet
Click on claim
Claim successfully Red Tent and Celo G$ UBI
observe post-claim screen
observe feed display
<img width="469" alt="Screenshot 2024-09-25 at 11 42 36 AM" src="https://github.com/user-attachments/assets/34367d71-edd2-4d9f-8173-e8dd85f8e3ea">
<img width="467" alt="Screenshot 2024-09-25 at 11 42 28 AM" src="https://github.com/user-attachments/assets/db73a1ad-2a6a-4057-a130-8dd742fbde7a">

**Expected Behavior**
Claim time should be the same time in the same format
Claim date should be the same date in the same format 

Please reference current feed item format (OK if type size, color etc is different but format and values should be the same).

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on prod
