### ISSUE TITLE
GoodID Upgrade - Misc Copy Updates

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodWeb3-Mono#201]
Please see the following screenshots for comments of what needs to be updated in each screen!

<img width="265" alt="Screenshot 2024-09-30 at 10 22 26 AM" src="https://github.com/user-attachments/assets/8f12e2c2-c2c6-42bb-bc2a-32b13e95e963">
<img width="478" alt="Screenshot 2024-09-30 at 10 33 04 AM" src="https://github.com/user-attachments/assets/4f4e37ad-f96b-4755-bbdc-fd07db7e3ef8">

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on prod
