### ISSUE TITLE
Feature: add support for i18n / custom copy's

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#57]
to support i18n we need to have an option to pass custom title.
             let this text be default prop +option to pass any other title from the protocol side 
             the same for the other texts I think (need to creat separate issue, discuss it with @sirpy and @patpedrosa )

_Originally posted by @johnsmith-gooddollar in https://github.com/GoodDollar/GoodWeb3-Mono/pull/55#discussion_r1120683869_

**Comment by L03TJ3** [comment]
@sirpy @patpedrosa @johnsmith-gooddollar 

So either we find a way to support i18n (to translate)
Or we figure out a solution which makes it easier to use custom copies in good-design components
What we current do is not scalable

**Comment by L03TJ3** [comment]
@decentralauren a ticket around supporting translations for gooddapp.
Older features that were build locally in gooddapp are accounted for in crowdin (have you been there already?)

Anything new build we don't have translatable copies for

**Comment by decentralauren** [comment]
- no active system for people to contribute to translate
[ ] test out automated / AI-based translation (with human editing) - @decentralauren 
[ ] solution for Support content, also 
- need a solution for all new screens (everything we have is stored locally). 
-- Decision: we are only going to support updating translations for GoodDapp and Support content.

**Comment by decentralauren** [comment]
Not relevant - have new translation flow
