### ISSUE TITLE
Torus should be a default wallet

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodWeb3-Mono#67]
### Description
As a hotfix torus was removed as default from onboard-sdk.
Torus should be added back, and wallet-specific customization options should be added to the onboard provider

- [ ] - Re-add torus as default wallet
- [ ] - Add custom wallet-options that can be set by using application IE. buildEnv for torus

*
- [ ] - Bonus points for adding ordering option to the wallet-list

**Comment by sirpy** [comment]
@L03TJ3 relevant?

**Comment by L03TJ3** [comment]
I think so yes
what has been done to solve it in production quickly was moving over the torus initialization to UI
the clean solution is to apply above options so that it the torus module is configurable
